USE [master]
GO

/****** Object:  Database [NW]    Script Date: 12-Jan-15 10:07:31 AM ******/
CREATE DATABASE [NW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NW.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\NW_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NW] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NW] SET ARITHABORT OFF 
GO

ALTER DATABASE [NW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NW] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NW] SET  MULTI_USER 
GO

ALTER DATABASE [NW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NW] SET  READ_WRITE 
GO

